Repository maticnetwork/heimdall, pull requests merged in 2020-03, with the labels that each got.

#234 Code quality: Add ci and linter
  .circleci/config.yml
  Makefile
  README.md
Labels: code-quality

#236 Implement MainTxMsg for topup msg
  topup/types/msg.go
Labels: bug

#259 Add rewards in staking details call
  contracts/stakinginfo/stakinginfo.abi
  contracts/stakinginfo/stakinginfo.go
Labels: contracts

#264 Add github workflow for linux-package
  .github/workflows/linuxpackage.yml
Labels: automation, code-quality

#268 Change validation period range [stateEpoch, endEpoch)
  types/validator.go
Labels: contracts

#251 Bridge
  Makefile
  bridge/cmd/purge.go
  bridge/cmd/start.go
  bridge/pier/ack.go
  bridge/pier/checkpoint.go
  bridge/pier/clerk.go
  bridge/pier/common.go
  bridge/pier/consumer.go
  bridge/pier/error.go
  bridge/pier/queue.go
  bridge/pier/span.go
  bridge/pier/syncer.go
  bridge/setu/broadcaster/broadcaster.go
  bridge/setu/broadcaster/broadcaster_test.go
  bridge/setu/listener/base.go
  bridge/setu/listener/heimdall.go
  bridge/setu/listener/maticchain.go
  bridge/setu/listener/rootchain.go
  bridge/setu/listener/service.go
  bridge/setu/processor/base.go
  bridge/setu/processor/checkpoint.go
  bridge/setu/processor/clerk.go
  bridge/setu/processor/fee.go
  bridge/setu/processor/service.go
  bridge/setu/processor/span.go
  bridge/setu/processor/staking.go
  bridge/setu/processor/types.go
  bridge/setu/queue/connector.go
  bridge/setu/util/common.go
  bridge/setu/util/db.go
  checkpoint/types/merkel.go
  go.mod
  go.sum
  helper/call.go
  helper/config.go
  helper/query.go
  helper/toml.go
  helper/tx.go
  staking/client/rest/query.go
  staking/keeper_test.go
  staking/querier.go
  staking/types/querier.go
  topup/client/rest/query.go
  topup/client/rest/rest.go
  topup/client/rest/tx.go
  types/account-proof.go
Labels: bridge, enhancement
