Repository maticnetwork/heimdall, pull requests merged in 2020-12, with the labels that each got.

#432 fix: proto format
  make/proto.mk
  proto/chainmanager/v1beta/genesis.proto
  proto/checkpoint/v1beta/genesis.proto
  proto/checkpoint/v1beta/querier.proto
  proto/cosmos/base/query/v1beta1/pagination.proto
  proto/cosmos/base/v1beta1/coin.proto
  proto/gov/v1beta/genesis.proto
  proto/gov/v1beta/gov.proto
  proto/heimdall/types/divident.proto
  proto/heimdall/types/headers.proto
  proto/heimdall/types/validator.proto
  proto/staking/v1beta1/genesis.proto
  proto/staking/v1beta1/msg.proto
  proto/staking/v1beta1/params.proto
Labels: automation, code quality

#442 Add dependabot, lint, proto, release, stale, test CI checks
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .github/workflows/proto.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  Makefile
  make/lint.mk
  make/test.mk
Labels: automation, code quality

#456 Fix formating
  app/app.go
  app/encoding.go
  file/perm_check.go
  file/perm_check_test.go
  go.mod
  go.sum
  helper/call.go
  helper/config.go
  helper/util.go
  make/lint.mk
  types/common/pubkey.go
  types/dividend-account.go
  types/rest/rest.go
  types/simulation/rand_util.go
  types/span.go
  x/chainmanager/genesis.go
  x/chainmanager/handler.go
  x/chainmanager/keeper/keeper.go
  x/chainmanager/keeper/querier.go
  x/chainmanager/module.go
  x/chainmanager/types/params.go
  x/checkpoint/genesis.go
  x/checkpoint/handler.go
  x/checkpoint/keeper/querier.go
  x/checkpoint/module.go
  x/gov/handler.go
  x/gov/keeper/keeper.go
  x/gov/keeper/querier.go
  x/gov/keeper/vote.go
  x/gov/module.go
  x/sidechannel/handler.go
  x/staking/genesis.go
  x/staking/handler.go
  x/staking/keeper/querier.go
  x/staking/module.go
  x/topup/handler.go
  x/topup/keeper/keeper.go
  x/topup/keeper/querier.go
  x/topup/module.go
Labels: automerge, code quality

#458 add grpc-gateway file generate command
  scripts/protoc-gen.sh
Labels: API, automerge, gRPC

#454 fixing gosimple linter errors
  app/app.go
  app/side_tx_processor_test.go
  cmd/heimdalld/cmd/init.go
  cmd/heimdalld/cmd/root.go
  file/perm_check.go
  types/bytes.go
  types/common/pubkey.go
  types/dividend-account.go
  types/rest/rest.go
  types/validator-set.go
  x/chainmanager/client/rest/rest.go
  x/checkpoint/client/rest/rest.go
  x/gov/client/rest/rest.go
  x/sidechannel/client/rest/rest.go
  x/sidechannel/keeper/keeper.go
  x/sidechannel/module.go
  x/staking/client/rest/rest.go
  x/staking/keeper/keeper.go
  x/topup/client/rest/rest.go
Labels: code quality

#452 Porting Staking Module
  app/app.go
  common/error.go
  go.mod
  go.sum
  helper/call.go
  helper/util.go
  proto/chainmanager/v1beta/genesis.proto
  proto/staking/v1beta1/msg.proto
  proto/staking/v1beta1/querier.proto
  x/chainmanager/keeper/keeper.go
  x/chainmanager/types/genesis.go
  x/chainmanager/types/genesis.pb.go
  x/chainmanager/types/params.go
  x/gov/types/gov.pb.go
  x/staking/client/cli/query.go
  x/staking/client/cli/tx.go
  x/staking/genesis.go
  x/staking/handler.go
  x/staking/keeper/grpc_query.go
  x/staking/keeper/keeper.go
  x/staking/keeper/msg_server.go
  x/staking/module.go
  x/staking/types/codec.go
  x/staking/types/events.go
  x/staking/types/msg.go
  x/staking/types/msg.pb.go
  x/staking/types/querier.go
  x/staking/types/querier.pb.go
  x/staking/types/querier.pb.gw.go
Labels: x/staking

#471 Serve swagger docs
  .gitignore
  app/app.go
  client/docs/config.json
  client/docs/cosmos-legacy-swagger.yaml
  client/docs/cosmos/auth/v1beta1/query.swagger.json
  client/docs/cosmos/bank/v1beta1/query.swagger.json
  client/docs/cosmos/params/v1beta1/query.swagger.json
  client/docs/statik/statik.go
  client/docs/swagger-ui/favicon-16x16.png
  client/docs/swagger-ui/favicon-32x32.png
  client/docs/swagger-ui/index.html
  client/docs/swagger-ui/oauth2-redirect.html
  client/docs/swagger-ui/swagger-ui-bundle.js
  client/docs/swagger-ui/swagger-ui-standalone-preset.js
  client/docs/swagger-ui/swagger-ui.css
  client/docs/swagger-ui/swagger.yaml
  common/error.go
  make/lint.mk
  proto/chainmanager/v1beta/query.proto
  proto/checkpoint/v1beta/query.proto
  proto/gov/v1beta/query.proto
  proto/staking/v1beta1/query.proto
  scripts/protoc-swagger-gen.sh
  x/chainmanager/types/params.go
  x/staking/types/msg.pb.go
  x/staking/types/querier.pb.go
Labels: API, automerge, docs

#460 Porting ChainManager Module
  app/app.go
  common/error.go
  proto/chainmanager/v1beta1/genesis.proto
  proto/chainmanager/v1beta1/query.proto
  x/chainmanager/client/cli/query.go
  x/chainmanager/client/cli/tx.go
  x/chainmanager/keeper/grpc_query.go
  x/chainmanager/module.go
  x/chainmanager/types/constants.go
  x/chainmanager/types/genesis.pb.go
  x/chainmanager/types/params.go
  x/chainmanager/types/querier.go
  x/chainmanager/types/query.pb.go
  x/chainmanager/types/query.pb.gw.go
  x/staking/module.go
  x/staking/side_handler.go
Labels: size: 5

#483 Update readme
  README.md
  x/chainmanager/types/params.go
  x/staking/types/query.pb.gw.go
Labels: automerge, docs
