Repository maticnetwork/heimdall, pull requests merged in 2020-04, with the labels that each got.

#297 mat-1037-check txbytes length while pulp decoding
  auth/types/pulp.go
Labels: automation

#300 MAT-1088 only allow one signer in tx and remove multi-send
  auth/ante.go
  bank/handler.go
  bank/keeper.go
  bank/types/codec.go
  bank/types/msg.go
Labels: bug

#293 Simulation tests
  app/app.go
  app/app_test.go
  app/config.go
  app/config_test.go
  app/helpers/test_helpers.go
  app/params/doc.go
  app/params/params.go
  app/params/weights.go
  app/sim_bench_test.go
  app/sim_test.go
  app/state.go
  app/test_helpers.go
  app/types.go
  app/utils.go
  app/utils_test.go
  auth/module.go
  auth/simulation/decoder.go
  auth/simulation/decoder_test.go
  auth/simulation/genesis.go
  auth/simulation/params.go
  auth/types/keys.go
  auth/types/params_test.go
  auth/types/stdtx_test.go
  bank/module.go
  bor/module.go
  bor/selection_test.go
  bor/shuffle_test.go
  chainmanager/module.go
  checkpoint/module.go
  clerk/module.go
  cmd/heimdalld/main.go
  gov/module.go
  simulation/doc.go
  simulation/event_stats.go
  simulation/log.go
  simulation/mock_tendermint.go
  simulation/operation.go
  simulation/params.go
  simulation/params_test.go
  simulation/simulate.go
  simulation/transition_matrix.go
  simulation/util.go
  staking/genesis.go
  staking/module.go
  staking/simulation/genesis.go
  supply/module.go
  topup/module.go
  types/module/module.go
  types/module/simulation.go
  types/simulation/account.go
  types/simulation/account_test.go
  types/simulation/config.go
  types/simulation/rand_util.go
  types/simulation/rand_util_test.go
  types/simulation/transition_matrix.go
  types/simulation/types.go
Labels: automation, code-quality

#294 Auth module testcases
  app/app.go
  app/genesis.go
  app/test_helpers.go
  auth/ante.go
  auth/ante_test.go
  auth/genesis_test.go
  auth/integration_test.go
  auth/keeper_test.go
  auth/module_test.go
  auth/querier_test.go
  auth/simulation/decoder_test.go
  auth/simulation/genesis.go
  auth/types/stdtx_test.go
  auth/types/test_common.go
  bank/genesis_test.go
  bank/integration_test.go
  bank/querier_test.go
  chainmanager/genesis_test.go
  chainmanager/integration_test.go
  chainmanager/keeper_test.go
  chainmanager/module.go
  chainmanager/querier_test.go
  chainmanager/simulation/genesis.go
  chainmanager/simulation/params.go
  chainmanager/types/genesis.go
  chainmanager/types/params.go
  helper/mocks/IContractCaller.go
  supply/keeper.go
  topup/genesis_test.go
  topup/handler.go
  topup/handler_test.go
  topup/intergration_test.go
  topup/keeper_test.go
  topup/module.go
  topup/querier.go
  topup/querier_test.go
  topup/simulation/genesis.go
  types/simulation/rand_util.go
Labels: DoNotMerge

#301 Validator unit tests
  types/validator.go
  types/validator_test.go
Labels: wip
