Repository maticnetwork/heimdall, pull requests merged in 2021-02, with the labels that each got.

#496 port clerk testcases
  app/app.go
  go.mod
  proto/chainmanager/v1beta1/genesis.proto
  proto/checkpoint/v1beta/genesis.proto
  proto/checkpoint/v1beta/msg.proto
  proto/clerk/v1beta/genesis.proto
  proto/clerk/v1beta/msg.proto
  proto/clerk/v1beta/query.proto
  proto/heimdall/types/validator.proto
  proto/sidechannel/v1beta1/genesis.proto
  proto/staking/v1beta1/genesis.proto
  proto/staking/v1beta1/msg.proto
  proto/topup/v1beta/genesis.proto
  proto/topup/v1beta/msg.proto
  proto/topup/v1beta/query.proto
  types/divident.pb.go
  x/checkpoint/types/genesis.pb.go
  x/clerk/client/cli/tx.go
  x/clerk/genesis_test.go
  x/clerk/handler_test.go
  x/clerk/keeper/keeper.go
  x/clerk/keeper/keeper_test.go
  x/clerk/keeper/msg_server.go
  x/clerk/module.go
  x/clerk/side_handler.go
  x/clerk/side_handler_test.go
  x/clerk/test_helper/test_helper.go
  x/clerk/types/clerk.pb.go
  x/gov/types/gov.pb.go
  x/staking/types/query.pb.gw.go
Labels: PR Raised, size: 8

#516 Test cases for Staking
  common/error.go
  helper/util.go
  mocks/IContractCaller.go
  x/staking/genesis_test.go
  x/staking/handler_test.go
  x/staking/keeper/grpc_query_test.go
  x/staking/keeper/keeper_test.go
  x/staking/side_handler.go
  x/staking/side_handler_test.go
  x/staking/simulation/utils.go
  x/staking/test_helper/test_helper.go
Labels: PR Raised, size: 8

#519 Topup test cases
  go.sum
  helper/call.go
  helper/mocks/IContractCaller.go
  types/dividend-account.go
  types/simulation/account.go
  x/checkpoint/types/merkle.go
  x/topup/genesis_test.go
  x/topup/handler_test.go
  x/topup/keeper/grpc_query_test.go
  x/topup/keeper/keeper.go
  x/topup/keeper/keeper_test.go
  x/topup/side_handler.go
  x/topup/side_handler_test.go
  x/topup/test_helper/test_helper.go
Labels: PR Raised, size: 8

#525 port govtestcases
  app/app.go
  app/mac.go
  proto/topup/v1beta/msg.proto
  x/clerk/handler_test.go
  x/clerk/keeper/msg_server.go
  x/clerk/side_handler.go
  x/clerk/side_handler_test.go
  x/gov/client/cli/parse_test.go
  x/gov/genesis.go
  x/gov/genesis_test.go
  x/gov/keeper/deposit.go
  x/gov/keeper/deposit_test.go
  x/gov/keeper/keeper.go
  x/gov/keeper/keeper_test.go
  x/gov/keeper/proposal.go
  x/gov/keeper/proposal_test.go
  x/gov/keeper/tally_test.go
  x/gov/keeper/vote.go
  x/gov/keeper/vote_test.go
  x/gov/module.go
  x/gov/test_helper/test_helper.go
  x/gov/types/codec.go
  x/gov/types/deposit.go
  x/gov/types/genesis.go
  x/gov/types/querier.go
  x/gov/types/tally.go
  x/gov/types/vote.go
Labels: in progress, size: 5

#549 Migrating Bor Module
  app/app.go
  client/docs/statik/statik.go
  common/error.go
  helper/util.go
  mocks/IContractCaller.go
  proto/heimdall/bor/v1beta1/bor.proto
  proto/heimdall/bor/v1beta1/genesis.proto
  proto/heimdall/bor/v1beta1/msg.proto
  proto/heimdall/bor/v1beta1/query.proto
  proto/heimdall/types/span.proto
  types/span.go
  types/span.pb.go
  types/validator.go
  x/bor/client/cli/flags.go
  x/bor/client/cli/query.go
  x/bor/client/cli/tx.go
  x/bor/genesis.go
  x/bor/handler.go
  x/bor/keeper/grpc_query.go
  x/bor/keeper/keeper.go
  x/bor/keeper/msg_server.go
  x/bor/keeper/query.go
  x/bor/keeper/selection.go
  x/bor/module.go
  x/bor/side_handler.go
  x/bor/types/bor.pb.go
  x/bor/types/codec.go
  x/bor/types/events.go
  x/bor/types/genesis.go
  x/bor/types/genesis.pb.go
  x/bor/types/keys.go
  x/bor/types/msg.go
  x/bor/types/msg.pb.go
  x/bor/types/msg.pb.gw.go
  x/bor/types/params.go
  x/bor/types/query.pb.go
  x/bor/types/query.pb.gw.go
  x/checkpoint/types/genesis.pb.go
  x/clerk/types/clerk.pb.go
  x/gov/types/gov.pb.go
  x/gov/types/query.pb.gw.go
  x/staking/types/query.pb.gw.go
Labels: PR Raised

#553 bor test cases
  x/bor/genesis_test.go
  x/bor/handler_test.go
  x/bor/keeper/grpc_query.go
  x/bor/keeper/grpc_query_test.go
  x/bor/keeper/keeper_test.go
  x/bor/keeper/selection_test.go
  x/bor/side_handler_test.go
  x/bor/test_helper/test_helper.go
Labels: PR Raised
